apiVersion: v1
kind: Pod
metadata:
  name: s-w-c
  labels:
    name: s-w-c
spec:
  containers:
  - name: s-w-c
    image: simple-webapp-color
    ports:
      - containerPort: 8080
    envFrom:
      - configMapRef:
          name: a-c      
